### PR TITLE
Updated source code

### PR DESCRIPTION
**Pull request by martinheidegger**
The current source of `dat-transform` doesn't work with the recent versions of hyperdrive in order to make it work, several things needed to change in the tests but the library basically works as before. Note that I completely refactored the tests: I didn't know what broke and had a hard time to figure things out.

### CODE REVIEW

**Comment by poga** [comment]
Thanks a lot!

Can you also update the example in the `README.md`? It's still using hyperdrive 7.

**Comment by martinheidegger** [comment]
Done, also added myself as contributor *cheers*

**Comment by poga** [comment]
Merged and published as `2.0.0` 🎉 

Btw, do you want to become a collaborator of this repo?

**Comment by martinheidegger** [comment]
Uhm, not really 😅- too many repos of my own.

**Comment by poga** [comment]
No pressure :D. Thanks for the great work!

**Pull request merged**
